version: 2
jobs:

  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build the Ruby image
          command: docker build -f Dockerfile.ruby .
  build-from-git:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build the Ruby image
          command: docker build -f Dockerfile.ruby-from-git .

workflows:
  version: 2
  check-dockerfiles:
    jobs:
      - build
      - build-from-git
